name: blocs
description: Blocs for training journal
version: 0.0.1
author:
homepage:

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.1.1
  flutter_secure_storage: ^3.3.3
  equatable: ^1.2.3
  meta: ^1.1.8

  repositories:
    path: ../repositories

dev_dependencies:
