name: training_journal
description: A tracking app for climbing and lifting

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_appauth: ^0.9.1
  flutter_secure_storage: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  blocs:
    path: ../blocs
  repositories:
    path: ../repositories

flutter:
  uses-material-design: true
