name: repositories
description: Repositories for training journal
version: 0.0.1
author:
homepage:

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  protobuf: ^1.0.1
  grpc: ^2.9.0
  http: ^0.12.2
  equatable: ^1.2.3
  meta: ^1.1.8
  flutter_appauth: ^0.9.1
  # protobuf: ^2.0.0-nullsafety.1
  # grpc:
  #   git: git://github.com/grpc/grpc-dart.git

dev_dependencies:
